export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_ROLES_REPOSITORY = 'USER_ROLES_REPOSITORY';
export const POST_REPOSITORY = 'POST_REPOSITORY';
